export const layout = new Map<string, string>([
	["Q", "KeyQ"],
	["W", "KeyW"],
	["E", "KeyE"],
	["R", "KeyR"],
	["T", "KeyT"],
	["Y", "KeyY"],
	["U", "KeyU"],
	["I", "KeyI"],
	["O", "KeyO"],
	["P", "KeyP"],
	["A", "KeyA"],
	["S", "KeyS"],
	["D", "KeyD"],
	["F", "KeyF"],
	["G", "KeyG"],
	["H", "KeyH"],
	["J", "KeyJ"],
	["K", "KeyK"],
	["L", "KeyL"],
	["Z", "KeyZ"],
	["X", "KeyX"],
	["C", "KeyC"],
	["V", "KeyV"],
	["B", "KeyB"],
	["N", "KeyN"],
	["M", "KeyM"],
]);
