name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Init pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.16.1

      - name: Init node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install

      - name: Run test
        run: pnpm test

      - name: Build packages
        run: pnpm build

      - name: Publish
        run: pnpm publish:core
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Init pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.16.1

      - name: Init node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install

      - name: Build docs
        run: pnpm docs:build

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: packages/.vitepress/dist

  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Init pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 7.16.1

      - name: Init node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          registry-url: https://registry.npmjs.org/
          cache: pnpm

      - run: pnpm install

      - name: README
        run: pnpm generate:readme

      - name: CHANGELOG
        run: pnpm generate:changelog

      - name: Commit generated reports
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "docs: generate README and CHANGELOG"
          git push
